NUMPY ARRAYS

In [2]:
import numpy as np

In [5]:
### Creatin a one dimensional array in numpy using a regular python list or tuple
# Python list
array1_1D = np.array([1,2,3,4,5])
## tuple
array2_1D = np.array((2,7,9,10,11,12))
print(f'The fist array is {array1_1D}')
print(f'The second array is {array2_1D}')

The fist array is [1 2 3 4 5]
The second array is [ 2  7  9 10 11 12]


In [7]:
## Adding the datatype of the array using the dtype option
# 1D array with complex dtype
array1_1D = np.array([1,2,3,4,5],dtype='complex')
print(f'This is a complex 1D array {array1_1D}')

This is a complex 1D array [1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [8]:
## A float dtype
array2_1D = np.array((2,7,9,10,11,12),dtype='float')
print(f'This is a float 1D array {array2_1D}')

This is a float 1D array [ 2.  7.  9. 10. 11. 12.]


In [9]:
## Two dimensional array
num_arry_2d = np.array([(1,3,5),(2,4,6)])
print(f'Output: {num_arry_2d}')

Output: [[1 3 5]
 [2 4 6]]


In [10]:
## Special arrays
# Array with zeros
array_zeros =  np.zeros((2,3))
print('Output:')
array_zeros

Output:


array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# Array with ones
array_ones = np.ones((2,4))
print('Output:')
array_ones

Output:


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
## Empty array
array_empty = np.empty((3,3))
print('Output:')
array_empty

Output:


array([[0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 8.636e-321],
       [0.000e+000, 0.000e+000, 0.000e+000]])

CREATING NUMPY ARRAY USING THE EXISTING tuple or  list

In [15]:
## tuple
t1 = (20,40,35,60)
print(f'The one dimension array is {np.array(t1)}')

The one dimension array is [20 40 35 60]


In [16]:
# List
lis1 = [[80,90,78,83,91],[1,2,3,4,5]]
print(f'The multidimensional array is {np.array(lis1)}')

The multidimensional array is [[80 90 78 83 91]
 [ 1  2  3  4  5]]
