In [1]:
### Import numpy as np
import numpy as np

In [3]:
### Creating the numpy array
# 1D array
array1_1D = np.array([1,2,4,3])
print('Output:')
array1_1D

Output:


array([1, 2, 4, 3])

In [4]:
# Using a tuple
array2_1D = np.array((1,2,4,5))
print(f'The array is {array2_1D}')

The array is [1 2 4 5]


In [11]:
### 2D numpy array
array1_2D = np.array([1,2,3,4])
print(f'The 2 dimension array is {array1_2D}')

The 2 dimension array is [1 2 3 4]


SPECIFYING THE DATA TYPE OF AND ARRAY

In [12]:
array1_1D = np.array((5,7,2,9),dtype='complex')
array1_1D

array([5.+0.j, 7.+0.j, 2.+0.j, 9.+0.j])

In [13]:
array2_1D = np.array([5,3,1,8],dtype='float')
array2_1D

array([5., 3., 1., 8.])

In [16]:
### 2 Dimensional array
# Using yhe python tuple
array1_2D = np.array([(23,46,7,1),(3,9,2,5)])
array1_2D

array([[23, 46,  7,  1],
       [ 3,  9,  2,  5]])

In [17]:
## Using the python list
array2_2D = np.array([[1,2,4,5],[9,7,0,8]])
array2_2D

array([[1, 2, 4, 5],
       [9, 7, 0, 8]])

SPECIAL NUMPY ARRAY

In [18]:
## ZERO ARRAY
array_zeros = np.zeros((2,3))
array_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
## ONES ARRAY
array_ones = np.ones((3,4))
array_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
### EMPTY ARRAY
array_empty = np.empty((4,4))
array_empty

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.79109909e-307],
       [8.34441742e-308, 1.78022342e-306, 6.23058028e-307,
        9.79107872e-307],
       [6.89807188e-307, 7.56594375e-307, 6.23060065e-307,
        1.78021527e-306],
       [8.34454050e-308, 1.11261027e-306, 2.04712907e-306,
        3.49698923e-317]])

CREATING NUMPY ARRAYS USING A LIST OR TUPLE

In [22]:
## Python list
lis1 = [3,6,7,3]
array_l1 = np.array(lis1)
array_l1

array([3, 6, 7, 3])

In [23]:
## Python tuple
t1 = (4,9,8,2)
array_tup = np.array(t1)
array_tup

array([4, 9, 8, 2])

In [25]:
### COMBINING
array_cob = np.array([(lis1),(t1)])
array_cob

array([[3, 6, 7, 3],
       [4, 9, 8, 2]])